In [1]:
import os

import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

### cum se creeaza o imagine goala pe 3 canale de culoare

In [2]:
img = np.zeros((100, 100, 3), np.uint8)

print(img)

cv.imshow("Test", img)
cv.waitKey(0)
cv.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


### am calculat media imaginilor din colectie si am inlocuit pachul cu imaginea cu media cea mai apropiata

In [16]:
imgRef = cv.imread('imagineReferinta.jpg')
imgRef = cv.resize(imgRef, (1920, 1080))

dir = 'colectiiImagini/'

files = os.listdir(dir)

nrFiles = len(files)

medianPhotos = []
photos = []

for file in files:
    img = cv.imread(dir + file)
    img = cv.resize(img, (15, 10))
    med = np.mean(img)
    medianPhotos.append(med)
    photos.append(img)


sortedMedianPhotos = np.sort(medianPhotos)

for i in range(0, 108):
    for j in range(0, 128):
        crop = imgRef[i * 10: (i + 1) * 10, j * 15: (j + 1) * 15, :].copy()
        cropMedian = np.mean(crop)

        closestMedianPhoto = 0

        for k in sortedMedianPhotos:
            if(cropMedian < k):
                closestMedianPhoto = k
                break

        index = 0

        for k in medianPhotos:
            if(k == closestMedianPhoto):
                break
            index += 1

        imgRef[i * 10: (i + 1) * 10, j * 15: (j + 1) * 15, :] = photos[index - 1]


cv.imshow("img noua", imgRef)
cv.waitKey(0)
cv.destroyAllWindows()

